### PR TITLE
Fix for issue #153: add a simple readme to all pkgs

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

May expand these in the future, if/when necessary.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@shaun-edwards: could you take a look?

**Comment by shaun-edwards** [comment]
+1...Are these used by the wiki or rosindex?

**Comment by gavanderhoorn** [comment]
The wiki doesn't use them (yet). rosindex will display them, but I was more thinking of users just installing the pkgs using `apt-get install ..` and then looking for some information in `roscd fanuc_whatever`. The fact that you should look on the ROS wiki isn't as obvious as we (or at least I) all assume(d), it appears.

**Comment by gavanderhoorn** [comment]
Thanks @shaun-edwards.

**Pull request merged**
