### PR TITLE
Catch up with latest industrial_ci updates

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

Slightly less verbose logs and hopefully faster builds by using cached workspaces.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: could you review?

**Comment by gavanderhoorn** [comment]
:bellhop_bell:

**Comment by gavanderhoorn** [comment]
:bellhop_bell:

**Review by shaun-edwards — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thank you @shaun-edwards.

We need to find a way to avoid these long in-review periods. In this case it's my own PR, but it's not nice in any case.

**Pull request merged**
