### PR TITLE
Fix for issue #176: invalid token in launch files failing roslaunch test

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per title.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@shaun-edwards: shouldn't be too hard.

**Comment by gavanderhoorn** [comment]
Friendly ping (so I can get the tests to pass gain).

**Comment by shaun-edwards** [comment]
+1

**Comment by gavanderhoorn** [comment]
Thanks @shaun-edwards.

**Pull request merged**
