### PR TITLE
Fix for issue #166: update support pkgs to use Roboguide colours

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

No functional changes, this is all purely cosmetic.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@JeremyZoss: would you be willing to take a quick look?

**Comment by JeremyZoss** [comment]
I think the explicit 12-digit color definitions are excessive.  You should be able to use your new color/material definitions for:
- `0.239215686275` is `color_fanuc_gray24`
- `0.278431372549` is `color_fanuc_gray28`
- `0.901960784314` is `color_fanuc_E6E6E6`

**Comment by gavanderhoorn** [comment]
> I think the explicit 12-digit color definitions are excessive.

If I had to do that manually for every urdf I'd agree, but they are just the result of `xacro` evaluating the arithmetic expression in `color_fanuc_gray24` (from [here](https://github.com/ros-industrial/fanuc/blob/a859053f5b601012d279e74a7d769c8b428640fc/fanuc_resources/urdf/common_colours.xacro#L13)):

``` xml
<xacro:property name="color_fanuc_gray24" value="${ 61/255} ${ 61/255} ${ 61/255} 1.0" />
```

Afaik there is no way to influence the nr of digits that is used to represent that result.

As you can see in [lrmate200ic5f_macro.xacro](https://github.com/ros-industrial/fanuc/pull/167/files#diff-dab3ecc0b8833d4fb542ac49640f759f) fi, the material macros are actually used.

**Comment by JeremyZoss** [comment]
Oops!  My bad.  I read through too quickly, and missed the distinction between xacro and urdf changes.

Perhaps things would look cleaner if the `<xacro:macro name="material_fanuc_grey">` macros from #164 were updated to use a non-blank material name?  Then, the XACRO files could refer to the material by name, rather than explicitly listing the RGBA code.  You'd probably need to call the macro for the first link, and just use a string-name for the other links.

This PR is okay as is, but consider whether you like the string-name option better...

**Comment by gavanderhoorn** [comment]
> Perhaps things would look cleaner if the `<xacro:macro name="material_fanuc_grey">` macros from #164 were updated to use a non-blank material name?  Then, the XACRO files could refer to the material by name, rather than explicitly listing the RGBA code.  You'd probably need to call the macro for the first link, and just use a string-name for the other links.

Yes, I considered that when I first introduced the `fanuc_assets` pkg (precursor to `fanuc_resources`). The reasons I eventually chose to use anonymous materials were:
1. I wasn't really convinced it was more efficient: both macro stanzas and named material references are a single line
2. you have to 'remember' that the first 'instance' of a material should be the macro invocation, the rest should not be (asymmetry)
3. potential for clashes: if you happen to have two macro stanzas 'at the same level' (or scope, but `xacro` doesn't have real scopes, at least not yet (see [wiki/xacro - Local properties](http://wiki.ros.org/xacro#Local_properties))), you'll end up with two material definitions with the same name. `xacro` doesn't seem to care, but other libs parsing urdf do: `[ERROR] [/robot_state_publisher]: material 'your_material' is not unique.`

So in the end I just figured that anonymous materials made the most sense: easy to use, no clashes possible (as they have no name) and the urdfs are not normally 'visible' anyway (most 'serious' projects use `xacro`, and the resulting urdf only 'appears' in the `robot_description` parameter(s)).

**Comment by gavanderhoorn** [comment]
Btw: two stanzas clashing is not so much an issue in a single xacro macro where you have all control over the content (as is the case with the macros in our support pkgs), but with _composite_ xacros created by other users.

**Comment by JeremyZoss** [comment]
Agreed.  Just wanted to document those rationale here.

+1. Merge when ready.

**Comment by gavanderhoorn** [comment]
Thanks for your comments again, @JeremyZoss.

**Pull request merged**
