### PR TITLE
readme: add license badges.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject. [Rendered version](https://github.com/ros-industrial/fanuc/blob/992e4d85d9f026749e90d08e3e509e0ce5e6f5b0/readme.md).

This ties in with #242 a bit, but not enough to add it there I believe.

This was done manually, but there are tools that can do this for you. I haven't looked at those yet though.

No functional changes, just a readme update.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@ipa-nhg: could you take a look?

If we are ok with this I think it would be a nice addition to all readmes.

(this is essentially an 'example PR'. We can open an issue over at `ros_industrial_issues` to coordinate later)

**Comment by NadiaHG** [comment]
@gavanderhoorn sure, I will check this. I will look for a tool that generate the badge automatically otherwise I will create a short bash script, should be easy. 

could we create a generic repository for these things? A generic repo to host templates, tools/script and short instructions to use them.what do you think?

**Comment by gavanderhoorn** [comment]
That all souds like a good idea, but initially I was just wondering whether you could review the PR itself.

I'll merge.

The rest we can discuss in an issue over at `ros_industrial_issues`. Whether we add license badges manually or use a tool is not something I find too important at the moment.

**Review by NadiaHG — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks @ipa-nhg.

Let's discuss this over at `ros_industrial_issues`.

**Pull request merged**
