### PR TITLE
Migrate M-20iB support and moveit pkgs from experimental repository

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

This migrates all packages related to the M-20iB from `fanuc_experimental` to `fanuc`, with the commit history that touches those packages.

This obviously leads to duplicate commits (as many touch multiple packages) and changes hashes, but there is no way to maintain the original commits while also importing them into this repository. At least this way the full history is present here as well. PR and issue references have been updated where necessary to still refer to `fanuc_experimental`.

No functional changes have been made to any of the packages. This is a straight import of the artefacts from `fanuc_experimental` with only some minor updates to the package manifests (such as references to `fanuc_experimental` and the wiki).

### CODE REVIEW

**Review by shaun-edwards — APPROVED** [review]
CI seems to have a problem though

**Comment by gavanderhoorn** [comment]
> CI seems to have a problem though

This is a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/). Checks don't get run for those.

I'd like to move everything M-20iB over in one go, and ros-industrial/fanuc_experimental#37 isn't merged yet, hence the draft (to avoid pressing *merge* by accident).

**Comment by gavanderhoorn** [comment]
ros-industrial/fanuc_experimental#45 replaces ros-industrial/fanuc_experimental#37.

Once ros-industrial/fanuc_experimental#45 gets merged, I'll complete the migration of the M-20iB packages and update the status of this PR.

**Comment by gavanderhoorn** [comment]
Thanks for the review @shaun-edwards :+1:

**Pull request merged**
