### PR TITLE
Port functionality to ROS on Windows

### PR DESCRIPTION
**Pull request by kokkalisko**
First port for windows 

- Adjust ikfast "scripts" for successfull MSVC compilation
- Change README.md

### CODE REVIEW

**Comment by kokkalisko** [comment]
PR mistakenly created. My apologies

**Comment by gavanderhoorn** [comment]
So where were you going to submit this PR?

---

Edit: I guess [here](https://github.com/kokkalisko/fanuc_for_windows).

If I may ask: what's your rationale for doing that in a fork?

**Comment by kokkalisko** [comment]
Yes, this is the [fork](https://github.com/kokkalisko/fanuc_for_windows) in question. 

> If I may ask: what's your rationale for doing that in a fork?

I did not want to disturb the original repo with any changes I made and have the original as a starting point.
Are there any better suggestions?

**Comment by gavanderhoorn** [comment]
> > If I may ask: what's your rationale for doing that in a fork?
> 
> I did not want to disturb the original repo with any changes I made and have the original as a starting point.
> Are there any better suggestions?

It would make sense to me to see whether we can accommodate Windows users, which would be easiest if you submit any changes *upstream* (ie: here).

There is no risk of disturbing anything until it gets merged here, and that will only happen if/when things are proven to work.

**Comment by kokkalisko** [comment]
All the changes are minor and can be seen in the single commit of this closed PR.
They are just related to the fact that MSVC does not support variable length arrays. Thus, the arrays of the IKFast generated C++ "script" has been replaced by smart pointers. Do you think that we should proceed?

**Comment by gavanderhoorn** [comment]
Seeing as Kinetic is EOL and you're changes have been validated with Melodic (I guess Noetic will work as well), I'm going to create a `melodic-devel` branch and then we can retarget this PR.

Note: I will not do that right now (ie: today).

I'll probably go ahead and migrate everything to `opw_kinematics` immediately, so the changes to the IKFast plugins wouldn't need to be included.

Can you confirm the only change would then be `xacro.py` -> `xacro` in the `.launch` file?

**Comment by kokkalisko** [comment]
Yes I have manually tested both `fanuc_driver` (with special care) and many of the `moveit_config` packages. I can confirm that the only change would be that for a melodic compatibility

**Pull request closed without merging**
