### PR TITLE
Added the cr7ial

### PR DESCRIPTION
**Pull request by dniewinski**
Added the cr7ial.  Basic moveit config, tested on a real cr7 and in roboguide

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Hi, thanks for the PR 👍.

Before I review it, could I ask you to re-open it against [fanuc_experimental](https://github.com/ros-industrial/fanuc_experimental)? This is a new package and we tend to add those to experimental repositories first.

Also: afaik the CR range -- at least the `7` and `4` -- is not based on the LR Mate 200iC, but on the LR Mate 200iD (if you take the F/T sensor away, you basically end up with the 200iD). Did you have a specific reason for adding it to the 200iC package?

Finally: we currently don't have permission from Fanuc to distribute detailed CAD models with our support packages, so I would appreciate it if you could remove them from the PR. We re-use the collision models for both the `visual` and the `collision` quality meshes.

**Comment by gavanderhoorn** [comment]
As the CR range is really a separate range, I suggest we add this new model in a `fanuc_cr7ia_support` package. `fanuc_experimental` already has a `fanuc_cr35ia_support` package, and we could potentially add a `fanuc_cr_support` package, but that would a) be different from how we treat other series (there is no `fanuc_m_support` pkg fi) and b) would mean that *all* CR series robots (which I can see getting quite extensive) end up there.

I'm not entirely sure yet how to structure the CR series, but as it's in `fanuc_experimental` we can sort that out later and for now adding a package specific to the CR-7iA series will work.

**Comment by gavanderhoorn** [comment]
One other comment: I know the work you're doing, so just to make sure, use [fanuc_driver_exp](https://github.com/gavanderhoorn/fanuc_driver_exp) instead of `fanuc_driver`.

**Comment by dniewinski** [comment]
I will close this request, make the changes, and reopen against fanuc_experimental.

**Comment by gavanderhoorn** [comment]
Thanks.

Sorry for the trouble.

**Pull request closed without merging**
