### PR TITLE
Added OPW kinematics parameter file for M20iB/25

### PR DESCRIPTION
**Pull request by axx-man**

### CODE REVIEW

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks.

I'm assuming you're using this in one of your application deployments and thus know these values are correct?

**Comment by gavanderhoorn** [comment]
Also: commit seems to be associated with `@isys-vision.de` which is not registered (any more?) with your GH account.

Would you want to change that before merging?

**Comment by axx-man** [comment]
> Thanks.
> 
> I'm assuming you're using this in one of your application deployments and thus know these values are correct?

I looked up all values from the urdf of this robot and cross-checked with another fanuc robot where a opw config already exists. I am afraid, I could only test with a simulated robot at the moment since we do not have this model in reach right now.

And thanks for your hint, I associated the email address to my GH account.

**Comment by gavanderhoorn** [comment]
> I could only test with a simulated robot

that would be sufficient.

**Comment by axx-man** [comment]
> > I could only test with a simulated robot
> 
> that would be sufficient.

In this case you can consider this as tested :slightly_smiling_face: 
Thanks for reacting so fast.

**Comment by gavanderhoorn** [comment]
Thanks again :+1: 

(Note: I've squashed merged, so GH might not show things as merged)

**Pull request merged**
