### PR TITLE
driver: update safety stat press. abn. comment.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

No functional changes.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong 🛎 ?

**Comment by Levi-Armstrong** [comment]
:+1:  OK to merge

**Comment by gavanderhoorn** [comment]
Thanks @Levi-Armstrong.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks again :)

**Pull request merged**
