### PR TITLE
Add OPW kinematics parameter files

### PR DESCRIPTION
**Pull request by JeroenDM**
To get the ball rolling on issue #245, I added the kinematic parameters from [this](https://github.com/JeroenDM/wip_fanuc_opw_parameters) repository to the support packages.

***
For the file name, I went for `opw_kinematics_...` instead of `opw_params_...` suggested [here](https://github.com/ros-industrial/fanuc/compare/indigo-devel...gavanderhoorn:m10_opw_kinem) because it documents that these parameters are related to the robot kinematics.

As far as the parameter names go, I used the MoveIt specific `kinematic_solver_`, again because this documents what the parameters are for, and is backward compatible. But on this one, I'm also open to merge [this](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/compare/kinetic-devel...gavanderhoorn:generic_params) diff and remove the MoveIt specific name.

***
Based on the discussion in #245, I think it would be nice if the MoveIt setup assistant configures the plugin automatically. For example by adding this line to the launch file as suggested [here](https://github.com/ros-industrial/fanuc/compare/indigo-devel...gavanderhoorn:m10_opw_kinem):
```
<rosparam command="load" ns="manipulator" file="$(find fanuc_m10ia_support)/config/opw_params_m10ia.yaml"/>
```

Or as an alternative, the setup assistant could copy the parameters to the `kinematics.yaml` file.

***
I also like this idea of @simonschmeisser 

> I have another idea I would like to throw in here:
> While we seem to agree that deriving the parameters directly from URDF might be too difficult/impossible/error-prone ... we could still try to embed the OPW parameters into the URDF. There is support for loading YAML files from xacro, so we could put the parameters in a generic file in config and load this from _macro.xacro. It could then be added as a parameter/child nodes of tool_0 link. The MoveIt kinematics.yaml could then be completely generic again and other consumers like Descartes could either read the yaml/rosparam or be extended to parse the robot_description/urdf as well
> 
> Do you think this idea is worth a prototype?

I think this should be the responsibility of the MoveIt setup assistant, and not of the plugin.

If we fixed the way the plugin loads the parameters from the ROS parameter server, we can change as much as we want with the way these parameters end up there...

***
What do you think? @gavanderhoorn  @simonschmeisser 
The conversation in #245 was a long one, so I'm not sure I processed al the suggestions. :)

### CODE REVIEW

**Comment by JeroenDM** [comment]
**Note**
I used the recently introduced [forward kinematic test](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/commit/c1dfaa3ced19a09b7f75d76f472487ca5444656e) to check the parameters and then manually copy-pasted them in this repository.

**Comment by gavanderhoorn** [comment]
@JeroenDM: I've added a few commits here.

Would you be able/willing to add the parameters for the remaining models/variants as well?

**Comment by gavanderhoorn** [comment]
I'm going to merge this as soon as Travis tells me CI passes.

**Review by simonschmeisser — APPROVED** [review]
Quite verbose but I guess that doesn't hurt

**Comment by gavanderhoorn** [comment]
Contrary to something like the joint names `.yaml`s, OPW is not a universally known concept in ROS.

So I wanted to make sure users encountering these files would be able to understand what they are for, and how they could be used.

All too often I find configuration settings (in `.yaml`s or directly in `.launch` files) which have no accompanying documentation or comment whatsoever, which makes it difficult to understand what's going on.

Hence the comment.

**Comment by gavanderhoorn** [comment]
Travis is having difficulty reaching Canonical's servers. Bla.

**Review by gavanderhoorn — APPROVED** [review]
Thanks for the contribution @JeroenDM :+1: 

And thanks for making the plugin available.

**Comment by JeroenDM** [comment]
The files still use the old parameter prefix `kinematic_solver_`, which [changed](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/pull/41/files) to `opw_parameters_`.

> Would you be able/willing to add the parameters for the remaining models/variants as well?

I would, but not in the coming weeks. I have a little bit too much going on at the moment, sorry...

**Comment by JeroenDM** [comment]
> And thanks for making the plugin available.

It was a great way to learn online collaboration and git :)

**Comment by gavanderhoorn** [comment]
> The files still use the old parameter prefix `kinematic_solver_`, which [changed](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/pull/41/files) to `opw_parameters_`.

Ah, that was close. I literally hovered over the *Squash and merge* button when your comment appeared.

I should've paid more attention.

I'll fix the keys.

**Comment by JeroenDM** [comment]
> Ah, that was close. I literally hovered over the Squash and merge button when your comment appeared.

haha, I was in the middle of writing the comment when I saw your new comment appear and hit the comment button as fast as I could :)

**Comment by gavanderhoorn** [comment]
> The files still use the old parameter prefix `kinematic_solver_`, which [changed](https://github.com/JeroenDM/moveit_opw_kinematics_plugin/pull/41/files) to `opw_parameters_`.

It was actually `kinematics_solver_*` to `opw_kinematics_*`, so your comment confused me.

But 453d974 should fix this.

**Comment by JeroenDM** [comment]
I can quickly test it manually in a ROS workspace if you want, but it looks good to me now. I like the extra comment explaining what it is.

**Comment by gavanderhoorn** [comment]
> I can quickly test it manually in a ROS workspace if you want, but it looks good to me now. I like the extra comment explaining what it is.

I've actually done that here locally :)

Which was a good thing, as I discovered I'd used the wrong prefix for the keys .. *again* ..

**Comment by gavanderhoorn** [comment]
Thanks again for the contribution.

Now on to Melodic/Noetic and dropping the IKFast plugins.

**Pull request merged**
