### PR TITLE
Import M-10iA, M-20iA, M-16iB, M-430iA & LR Mate 200iC experimental pkgs

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

This PR imports the experimental support packages for the M-20iA (base & /10L) and the LR Mate 200iC (base, /5H, /5HS, /5L & /5F), as well as the MoveIt configuration and (IKFast) plugin packages for the M-10iA, M-20iA, M-16iB, M-430iA/2(F,P) and the LR Mate 200iC into the main repository.

No changes have been made to the packages (other than meta-data updates).

After acceptance of this PR, those packages will no longer be considered experimental and will be removed from the `fanuc_experimental` repository.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@shaun-edwards: if you could take a look?

**Comment by shaun-edwards** [comment]
Are these all the robot packages from `fanuc_experimental`?  

What criteria do we use to determine when a package should be transferred (this is more a general question, I'm not sure what the answer is)
- Have the packages been verified on physical (real or simulated) systems?
- Have others verified/used the packages
- Do the packages simply have to adhere to the package structure standards (is there an easy(automated) check for this)?

**Comment by gavanderhoorn** [comment]
@shaun-edwards wrote:

> Are these all the robot packages from `fanuc_experimental`?

No, this PR does not import the `lrmate_200id_support` and related packages. Those are not complete, have not been extensively tested (either by me, or someone else that I know of) and do not live up to my own 'quality criteria' (mesh quality fi).

> What criteria do we use to determine when a package should be transferred (this is more a general question, I'm not sure what the answer is)
> - Have the packages been verified on physical (real or simulated) systems?
> - Have others verified/used the packages

The criteria I've used:
- **age**: most of these (support) packages (in fact: all, except 2) have been in `fanuc_experimental` for at least a year. According to github repository statistics, the repository sees enough traffic to assume that if something serious was wrong with them, we'd have heard about it
- **community 'review'**: some time ago (October) I've sent out a message on the mailing list asking for user experiences with the pkgs in this PR, mentioning that I was planning to promote them to the non-experimental repository. I've received 2 private emails as a result of this, and have addressed the issues raised in those.
- **maturity**: the LR Mate 200iC package now supports all 'standard variants' of the robot (not including customisations or special options). The others are either 'complementary' packages (MoveIt configs, etc) or support the variants that are in use at the sites of some of our users.
- **use on real hardware**: the M-10iA, M-20iA, M-430iA/2F and LR Mate 200iC/5H, /5L and /5F have all been used on real hardware and have had their `base -> tool0` transform checked against data reported by the controller.
- **use in simulation**: all packages have been used with simulated hardware: this is actually standard practice for me whenever I make a new support package (or add a model to an existing one).

> - Do the packages simply have to adhere to the package structure standards (is there an easy(automated) check for this)?

Yes, I also consider this to be an important requirement, but also one of the first to fix. In my mind, something is not a _robot support package_ if it does not follow the (simple) guidelines we have for file and directory layout.

**Comment by gavanderhoorn** [comment]
Friendly ping?

**Comment by shaun-edwards** [comment]
+1...I looked through the directory/file structure but didn't go through all the details.  The process you followed above is adequate for transferring packages out of an experimental repo.  I still believe auto-generating packages is the next step to ensuring quality support packages.  This is something I hope to roll out (have documented) for indigo (this is just further motivation to do this).  Thanks for the contribution...feel free to merge.

**Comment by gavanderhoorn** [comment]
Thanks @shaun-edwards.

**Comment by gavanderhoorn** [comment]
And I agree that auto-generating the pkgs is the way to go (or at least, auto-generating as much as possible). Perhaps we should look into some sort of _support pkg lint_ tool as well.

**Pull request merged**
