### PR TITLE
Add colour definitions based on Roboguide colours

### PR DESCRIPTION
**Pull request by gavanderhoorn**
This PR adds a few material xacros for colours based on info from Roboguide. A future PR will update support pkgs to use these new definitions.

### CODE REVIEW

**Comment by shaun-edwards** [comment]
@JeremyZoss, can you please review.

**Comment by JeremyZoss** [comment]
Out of curiosity, where did these colors come from?  The default Fanuc robot in my RoboGuide cell seems to use `FFFF12` for yellow and `5C5C5C` (36% gray) for the base.  Other components seem to have freely-assignable RGB colors.

I think you can omit the "fanuc" from `color_fanuc_grayXX`, as these are absolute colors and not fanuc-specific.  No heartburn if you want to leave `fanuc` for namespace separation, though.

Any reason why `color_fanuc_E6E6E6` and not `color_fanuc_gray90`?

Use consistent spelling for `grey`/`gray`.  See `color_fanuc_grayXX` vs `color_fanuc_grey`.

All mostly trivial suggestions.  +1 from me.

**Comment by gavanderhoorn** [comment]
@JeremyZoss wrote:

> Out of curiosity, where did these colors come from?  The default Fanuc robot in my RoboGuide cell seems to use `FFFF12` for yellow and `5C5C5C` (36% gray) for the base.  Other components seem to have freely-assignable RGB colors.

The colours were taken from a selection of Roboguide workcell (`.frw`) files. It's a bit random, but in some files the colours for the base and body of the robot are stored as a property of the controller element.

Also: which specific model is it that uses those colours? Did you get those values from the workcell file or by using a screenshot?

> I think you can omit the "fanuc" from `color_fanuc_grayXX`, as these are absolute colors and not fanuc-specific.  No heartburn if you want to leave `fanuc` for namespace separation, though.

I agree that they may not be Fanuc specific, but as xacro properties / macros all seem to live in the same - flat - namespace, I adopted a prefix-everything style for naming to avoid possible name clashes. It is also in-line with other support pkgs, but seeing as these are colours that are indeed defined external to any particular vendor it might not be necessary.

> Any reason why `color_fanuc_E6E6E6` and not `color_fanuc_gray90`?

Simply because the site I used to look it up did not give me that name, so I opted to use the hex code instead. I'll change it.

> Use consistent spelling for `grey`/`gray`.  See `color_fanuc_grayXX` vs `color_fanuc_grey`.

Yes, I knew someone would notice that :). The `grey` one is 'old' and has been used in released pkgs, so I cannot just change it. I might add a new one and tick-tock them.

> All mostly trivial suggestions.  +1 from me.

thanks for your time.

**Comment by JeremyZoss** [comment]
> Also: which specific model is it that uses those colours? Did you get those values from the workcell file or by using a screenshot?

These came from an M-10iA/7L.  I got the colors from a screenshot, where I tried to minimize the lighting affects as much as possible.  Crude, I'll admit.

**Comment by gavanderhoorn** [comment]
@JeremyZoss wrote:

> Any reason why `color_fanuc_E6E6E6` and not `color_fanuc_gray90`?

Turns out that `E5E5E5` is [Gray 90](http://www.color-hex.com/color/e5e5e5). `E6E6E6` doesn't really have a name (see [here](http://www.color-hex.com/color/e6e6e6)). I'm going to keep it as it is.

> Use consistent spelling for `grey`/`gray`.  See `color_fanuc_grayXX` vs `color_fanuc_grey`.

As I wrote earlier, `grey` is the older one, and is actually RAL 7024 or [graphite grey](https://www.ralcolorchart.com/ral-7024-graphite-grey) (actual spelling). I can add an aliasing `gray`, but I don't think it really adds much.

**Comment by gavanderhoorn** [comment]
@JeremyZoss wrote:

> @gavanderhoorn wrote:
> 
> > Also: which specific model is it that uses those colours? Did you get those values from the workcell file or by using a screenshot?
> 
> These came from an M-10iA/7L.  I got the colors from a screenshot, where I tried to minimize the lighting affects as much as possible.  Crude, I'll admit.

Yes, that was what I did to get the values for the [approximations](https://github.com/ros-industrial/fanuc/blob/4fd56650eb6266af54bb414926f1bc7756234a22/fanuc_resources/urdf/common_colours.xacro#L11-L13). The values from the workcell files should avoid any influence of lighting, hence my desire to add them to the `resources` package.

**Comment by gavanderhoorn** [comment]
I've updated the PR. The properties now use arithmetic expressions for the RGB fractions instead of values between 0 and 1, which should make it a bit easier to compare them to their source data.

Other that that no real changes. Are you satisfied with the rationales / explanations given, @JeremyZoss?

**Comment by JeremyZoss** [comment]
Fine with me.  +1.  Merge when ready.

**Comment by gavanderhoorn** [comment]
Thanks @JeremyZoss for the review.

**Pull request merged**
