### PR TITLE
driver: increase Karel def loop rate to 42 Hz.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

See the commit msg of bde0ce4 for rationale.

Connects to #203 (specifically: https://github.com/ros-industrial/fanuc/issues/203#issuecomment-277713908).

### CODE REVIEW

**Comment by VictorLamoine** [comment]
You should also change the tables here after merging:
http://wiki.ros.org/fanuc/Tutorials/hydro/Configuration#KAREL_Programs

**Comment by gavanderhoorn** [comment]
Yes, good catch.

**Comment by gavanderhoorn** [comment]
@shaun-edwards: ping?

**Review by shaun-edwards — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Wiki updated: [ros_state config](http://wiki.ros.org/action/info/fanuc/ros_state_config_defaults_table?action=diff&rev2=5&rev1=4) and [ros_relay config](http://wiki.ros.org/action/info/fanuc/ros_relay_config_defaults_table?action=diff&rev2=6&rev1=5).

**Comment by gavanderhoorn** [comment]
Thanks for the check @shaun-edwards.

**Comment by gavanderhoorn** [comment]
And thanks for the pointer @VictorLamoine.

**Pull request merged**
