### PR TITLE
Minor updates to M-10iA/7L support

### PR DESCRIPTION
**Pull request by gavanderhoorn**
Some minor things were missing in #189, so this PR adds those.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@JeremyZoss: could you take a look?

**Comment by gavanderhoorn** [comment]
@JeremyZoss: in my experience variants of the same model can share some meshes. For `L` variants this typically at least includes the `base_link` and `link_1`, but for the `/7L` in #189 , it looks like even those are different from the base M-10iA.

According to the documentation I have, only `link_2` and `link_4` are longer, the rest seems (but I haven't explicitly verified this) like it is the same as the base model.

Could you tell me where you got the meshes from?

**Comment by JeremyZoss** [comment]
Meshes were exported IGS from RoboGuide, then wrapped in a Convex Hull for collision meshes.  This release uses those collision meshes for both Visual and Collision meshes, per our usual procedures.

**Comment by gavanderhoorn** [comment]
> Meshes were exported IGS from RoboGuide, [..]

Ah, ok. That probably explains the differences then (the base model meshes were converted from the SolidWorks assembly).

**Comment by gavanderhoorn** [comment]
Any comments on the changes in this PR?

**Comment by JeremyZoss** [comment]
It's still early yet this morning.  =)  First glance looks fine.  I haven't had time to do a test-run on my PC to confirm.  I'll be in meetings for the next 4-6 hrs, and unable to respond further.  Feel free to merge if you're comfortable with that level of review.

**Comment by gavanderhoorn** [comment]
No problem, I'll wait for your +1.

**Comment by gavanderhoorn** [comment]
Forgot: could you tell me which set of joint limits the xacro is based on? _Conventional Dress-out_ or something else?

**Comment by gavanderhoorn** [comment]
@JeremyZoss?

**Comment by JeremyZoss** [comment]
Sorry.

I based the joint limits on the standard Fanuc limits published [here](http://robot.fanucamerica.com/products/robots/productbyseries.aspx?seriesId=6&robotseries=M-10iA) ([pdf](http://www.fanucamerica.com/cmsmedia/datasheets/M-10iA%20and%20M-20iA%20Series_172.pdf)), double-checked against the actual controller configuration for asymmetric limits.  I'm not sure what dressout that corresponds to, as my documentation does not refer to those options.

**Comment by gavanderhoorn** [comment]
Ok. Based on the URDF I'm pretty sure this is a _Conventional Dress-out_ system:

dress_out

with J1 range set to `[-170, 170]`:

j1_range

I'll add that to the manifest.

**Comment by gavanderhoorn** [comment]
Manifest updated.

**Comment by gavanderhoorn** [comment]
@JeremyZoss: are you ok with me merging this PR?

**Comment by gavanderhoorn** [comment]
I'll merge this PR if no further comments are made before EOB.

**Comment by JeremyZoss** [comment]
+1.  Merge away.

**Comment by gavanderhoorn** [comment]
Thanks @JeremyZoss.

And also again for #189.

**Pull request merged**
