### PR TITLE
travis: enable Kinetic and Melodic builds.

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

In preparation for a Kinetic release.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
This currently fails due to the Python scripts in `warehouse_ros` having been removed in ros-planning/warehouse_ros#32 and they won't come back.

All `*_moveit_config` packages in `fanuc` contain `roslaunch` tests which attempt to load the `moveit_planning_execution.launch` file, which in turn (ultimately) tries to load the Python node(s) in `warehouse_ros` ([here](https://github.com/ros-industrial/fanuc/blob/05b3e157e000678d8c7830d88367b03d238a8bfd/fanuc_lrmate200i_moveit_config/tests/moveit_planning_execution.xml) fi).

**Comment by gavanderhoorn** [comment]
Disabling the `roslaunch` tests that enable the DB infrastructure (which depends on `warehouse_ros`) makes CI succeed again.

I'll log an issue to track the state of `warehouse_ros` as used with MoveIt configurations, so as to be reminded to re-enable them at a later time when possible.

**Comment by gavanderhoorn** [comment]
I believe this is ready for a review now.

If one of you could review, I'll merge.

**Comment by gavanderhoorn** [comment]
:bellhop_bell:

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Thanks @Levi-Armstrong.

**Pull request merged**
