### PR TITLE
Added m6ib/6s (variant of FANUC m6ib ): fix of #259

### PR DESCRIPTION
**Pull request by joao-pm-santos96**
Sorry for the new pull request, made several mistakes in the previous fork, so decided to make a new one in the hope it helps. Only thing different from pull request #259 is the addition of IKFAST solver for the m6ib6s.

Using help from @gavanderhoorn and @miguelriemoliveira I was able to adapt the fanuc_m6ib_support and moveit_config of the M6ib in order to get a functional version of the M6ib/6s.

Tested with real robot and works.

CAD changes from original m6ib (not precisely accurate but sufficient).

image

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@joao-pm-santos96: thanks for the PR. And my apologies for taking so long to review it.

If you're still around: am I correct when I believe you've taken the `.stl`s from the base M-6iB and changed them to fit the geometry of the M-6iB/6S? I'm not sure that is something we should do. `link_2.stl` looks a bit strange for instance that way: [fanuc_m6ib_support/meshes/m6ib6s/visual/link_2.stl](https://github.com/ros-industrial/fanuc/blob/c04a2d938bc7a77bd39f0edfffcdde4299280863/fanuc_m6ib_support/meshes/m6ib6s/visual/link_2.stl)

I'll see if I can find some proper meshes for the `/6S` and add those.

**Comment by joao-pm-santos96** [comment]
Hello @gavanderhoorn, you are absolutely right, yet only links 2 and 4 where changed. It was the best solution I could find with what I had available and to the extent that my thesis requested, it worked pretty well. But with no doubt, it could look better.

**Comment by gavanderhoorn** [comment]
I've found the meshes and will update the PR.

**Comment by joao-pm-santos96** [comment]
That is great news!! Thanks!!

**Comment by gavanderhoorn** [comment]
@joao-pm-santos96: I notice that the IKFast plugin isn't actually being built in the version of `fanuc_m6ib_moveit_plugins` that you included in the PR.

Did you build everything in the PR? Or was the IKFast plugin added with the file & folder layout after you built it in a stand-alone package? [This one](https://github.com/lardemua/SmObEx/tree/74866504608515bfd8db804f271a180d2a8ac752/fanuc_m6ib6s_moveit_plugins) perhaps?

Adding the necessary plugin exports and statements to `CMakeLists.txt`, I get the following errors:

<details>
<summary>Compiler error</summary>

```c++
/home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:324:8: error: ‘bool fanuc_m6ib6s_manipulator::IKFastKinematicsPlugin::initialize(const moveit::core::RobotModel&, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, double)’ marked ‘override’, but does not override
   bool initialize(const moveit::core::RobotModel& robot_model, const std::string& group_name,
        ^
/home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp: In member function ‘bool fanuc_m6ib6s_manipulator::IKFastKinematicsPlugin::computeRelativeTransform(const string&, const string&, Eigen::Isometry3d&, bool&)’:
/home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:377:36: error: ‘robot_model_’ was not declared in this scope
   robot_state.reset(new RobotState(robot_model_));
                                    ^
/home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp: In member function ‘bool fanuc_m6ib6s_manipulator::IKFastKinematicsPlugin::initialize(const moveit::core::RobotModel&, const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, double)’:
/home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:410:85: error: ‘storeValues’ was not declared in this scope
   storeValues(robot_model, group_name, base_frame, tip_frames, search_discretization);
                                                                                     ^
/home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:436:46: error: ‘robot_model_’ was not declared in this scope
   const moveit::core::JointModelGroup* jmg = robot_model_->getJointModelGroup(group_name);
                                              ^
In file included from /usr/include/eigen3/Eigen/Geometry:44:0,
                 from /opt/ros/kinetic/include/moveit/robot_model/joint_model.h:47,
                 from /opt/ros/kinetic/include/moveit/robot_model/joint_model_group.h:41,
                 from /opt/ros/kinetic/include/moveit/robot_model/robot_model.h:47,
                 from /opt/ros/kinetic/include/moveit/robot_state/robot_state.h:41,
                 from /home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:46:
/usr/include/eigen3/Eigen/src/Geometry/Transform.h: In instantiation of ‘Eigen::Transform<Scalar, Dim, Mode, _Options>::Transform(const Eigen::Transform<_Scalar, Dim, OtherMode, OtherOptions>&) [with int OtherMode = 2; int OtherOptions = 0; _Scalar = double; int _Dim = 3; int _Mode = 1; int _Options = 0]’:
/home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:395:13:   required from here
/usr/include/eigen3/Eigen/src/Geometry/Transform.h:330:5: error: static assertion failed: YOU_PERFORMED_AN_INVALID_TRANSFORMATION_CONVERSION
     EIGEN_STATIC_ASSERT(EIGEN_IMPLIES(OtherMode==int(Affine)||OtherMode==int(AffineCompact), Mode!=int(Isometry)),
     ^
In file included from /opt/ros/kinetic/include/class_loader/class_loader_core.hpp:46:0,
                 from /opt/ros/kinetic/include/class_loader/./class_loader.hpp:43,
                 from /opt/ros/kinetic/include/class_loader/class_loader.h:35,
                 from /opt/ros/kinetic/include/pluginlib/class_list_macros.hpp:40,
                 from /home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:1374:
/opt/ros/kinetic/include/class_loader/meta_object.hpp: In instantiation of ‘B* class_loader::class_loader_private::MetaObject<C, B>::create() const [with C = fanuc_m6ib6s_manipulator::IKFastKinematicsPlugin; B = kinematics::KinematicsBase]’:
/home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:1375:201:   required from here
/opt/ros/kinetic/include/class_loader/meta_object.hpp:198:16: error: invalid new-expression of abstract class type ‘fanuc_m6ib6s_manipulator::IKFastKinematicsPlugin’
     return new C;
                ^
/home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:154:7: note:   because the following virtual functions are pure within ‘fanuc_m6ib6s_manipulator::IKFastKinematicsPlugin’:
 class IKFastKinematicsPlugin : public kinematics::KinematicsBase
       ^
In file included from /home/user/src/fanuc/fanuc_m6ib_moveit_plugins/m6ib6s_kinematics/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp:45:0:
/opt/ros/kinetic/include/moveit/kinematics_base/kinematics_base.h:370:16: note: 	virtual bool kinematics::KinematicsBase::initialize(const string&, const string&, const string&, const string&, double)
   virtual bool initialize(const std::string& robot_description, const std::string& group_name,
                ^
make[2]: *** [m6ib6s_kinematics/CMakeFiles/fanuc_m6ib6s_manipulator_moveit_ikfast_plugin.dir/src/fanuc_m6ib6s_manipulator_ikfast_moveit_plugin.cpp.o] Error 1
make[1]: *** [m6ib6s_kinematics/CMakeFiles/fanuc_m6ib6s_manipulator_moveit_ikfast_plugin.dir/all] Error 2
make: *** [all] Error 2
```

</details>

Did you generate the plugin under Kinetic or under Melodic?

**Comment by gavanderhoorn** [comment]
I've added some commits that fix various issues. Most importantly I've added the correct meshes for the `/6S`, and reused the meshes of the base model as much as possible.

**Comment by joao-pm-santos96** [comment]
Hello @gavanderhoorn. I had so many issues dealing with IKFast, that I can be 100% sure, but as the most as I can remember, the one that is in this PR is not the same that is in the [SmObEx](https://github.com/lardemua/SmObEx/tree/74866504608515bfd8db804f271a180d2a8ac752/fanuc_m6ib6s_moveit_plugins) package. The one that is in the SmObEx package is actually working but I never integrated it in this PR because I've had joint limits problems (not sure from the plugin or the manipulator itself) that I had to solve in joint limits impose in c++ code. Nonetheless, the plugin in this PR was generated under Kinetic.

**Comment by gavanderhoorn** [comment]
Ok.

For now I think I'm going to merge your PR without the IKFast plugin.

I'll update the MoveIt configuration to use Trac-IK until the IKFast plugin is available.

**Comment by joao-pm-santos96** [comment]
That is awesome! @miguelriemoliveira will be very happy to know! 

Thank you for your support @gavanderhoorn !!

**Comment by miguelriemoliveira** [comment]
Yes, these are great news. Thank you both!

**Comment by gavanderhoorn** [comment]
I've opened a replacement PR in #277.

Main differences: uses the correct meshes (for just `link_2` and `link_4`) and doesn't include the IKFast plugin.

**Comment by gavanderhoorn** [comment]
Attribution of the commits and the work is maintained in #277.

Many thanks @joao-pm-santos96 :+1: 

Apologies for taking so long to merge this in.

**Comment by gavanderhoorn** [comment]
I just merged #277 @joao-pm-santos96.

Thanks again for the contribution.

Your SmObEx looks like a nice project.

**Pull request closed without merging**
