### PR TITLE
Fix issue #83: add comments to TP Ps, PRs and Fs

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

These will be applied to the actual Ps, PRs and Fs on the controller when the `.tp` is loaded.

No functional changes.

This is a draft for now, as I need to verify this on real hw.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
#83.

**Comment by gavanderhoorn** [comment]
If any of you could review, I'll merge.

**Review by dejaniraai — APPROVED** [review]
I have taken a look at the changes and they seem fine.

**Comment by gavanderhoorn** [comment]
Thanks again @dejaniraai :+1:

**Pull request merged**
