### PR TITLE
added m6ib/6s moveit plugin with ikfast

### PR DESCRIPTION
**Pull request by joao-pm-santos96**
In this PR we added the M6iB/6S MoveIt Plugins package, generated with the IKFast plugin, accordingly to http://docs.ros.org/indigo/api/moveit_tutorials/html/doc/ikfast_tutorial.html and a discussion can be found [here](https://github.com/lardemua/SmObEx/issues/21)

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
You link the Indigo tutorials. Is that because you generated this on Trusty/Indigo? IKFast plugin infrastructure has changed significantly recent years, so I'd like to make sure.

Build is currently failing on Kinetic, but before we start looking into this, it'd be good to clarify your build environment and targeted MoveIt version.

**Comment by joao-pm-santos96** [comment]
Actually this package was built many moths ago... yesterday I tried and successfully compiled it on Ubuntu 18.04 with ROS Melodic. The actually tutorial was [this one](https://acutronicrobotics.com/docs/products/robots/mara/moveit2/tutorials/ros/ikfast) but is now inaccessible...

**Comment by gavanderhoorn** [comment]
> yesterday I tried and successfully compiled it on Ubuntu 18.04 with ROS Melodic.

Yes, CI also succeeds for Melodic. But it fails for Kinetic.

As we're supporting both Kinetic and Melodic here, this PR cannot be merged until both versions of the build succeed.

>  The actually tutorial was [this one](https://acutronicrobotics.com/docs/products/robots/mara/moveit2/tutorials/ros/ikfast) but is now inaccessible...

Accutronics robotics doesn't exist any more, so their servers and other infrastructure has also been taken down.

**Comment by joao-pm-santos96** [comment]
Rebuilted the package on kinetic (following [this tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/ikfast/ikfast_tutorial.html)) and now compiles on both kinetic and melodic. Do you confirm?

Have not tested in a real robot though..

**Pull request closed without merging**
